### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/Natural-Language-Database-Querying#1]
- [ ] Build GUI
- [ ] Find best model for tagging frames in videos (less time, more objects)
- [ ] Create a tagged database
- [ ] Creation of vector space for the query, video
- [ ] Data Retrieval from database
- [ ] Possibility of learning from queries made to improve tags? (keyword found in the query but not found in keywords of video, add to video tags?)
- [ ] Possibility of using video attributes such as the title of the video to tag?
- [ ] Watson sentiment, emotion matching - can these be used?
- [ ] Find limit of duration for recognize_google 
- [ ] Cleaning up of keywords has to be done. 
	- [ ]  Remove same name duplicates
	- [ ] Keep only most similar keywords (step might be needed multiple times)
- [ ] Visit the URL and extract full title for google image search
- [ ] video frames for tagging -> frames -> objects in frames -> most occuring objects in video
                                               filtered frames -> frames containing most occuring object
	                                       -> frame rate?
